variables:
    PATH_PROJECT: "/home/onlineshop/online-shop-backend/"
    USER_PROJECT: "onlineshop"
    IMAGE_VERSION: "$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA"
    CODECLIMATE_FILE: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_codeclimate"
    SNYKSCAN_FILE: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_snykscan"
stages:
    - build
    - test source code
    - deploy

build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - docker build -t ${IMAGE_VERSION} .
    tags: 
        - online-shop-runner-dev-shell

test source code:
    stage: test source code
    variables:
        GIT_STRATEGY: none
    script:
        - docker run --interactive --platform linux/amd64 --rm -e CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f html> $CODECLIMATE_FILE.html
    tags:
        - online-shop-runner-dev-shell
    artifacts:
        paths:
        - $CODECLIMATE_FILE.html
        expire_in: 1 day

snykscan:
    stage: test source code
    variables:
        GIT_STRATEGY: clone
    script:
        - docker build --rm --network host --build-arg SNYK_AUTH_TOKEN=$SNYK_TOKEN --build-arg OUTPUT_FILENAME=$SNYKSCAN_FILE -t $SNYKSCAN_FILE -f Dockerfile-snyk .
        - docker create --name $SNYKSCAN_FILE $SNYKSCAN_FILE
        - docker cp $SNYKSCAN_FILE:/app/$SNYKSCAN_FILE.html .
    tags:
        - online-shop-runner-dev-shell
    artifacts:
        paths:
        - $SNYKSCAN_FILE.html
        expire_in: 1 day

deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - sudo su ${USER_PROJECT} -c "docker rm -f $CI_PROJECT_NAME; docker run --name $CI_PROJECT_NAME -dp '5214:5214' ${IMAGE_VERSION}"
    tags: 
        - online-shop-runner-dev-shell

